[server]
port = 10000
enableCORS = true
enableXsrfProtection = false
maxUploadSize = 200
maxMessageSize = 200

[browser]
serverAddress = "localhost"
gatherUsageStats = false

[theme]
primaryColor = "#FF4B4B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[logger]
level = "info"

[client]
showErrorDetails = true
toolbarMode = "auto"

[runner]
fastReruns = true
